# Generated by Django 2.0 on 2017-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomiar',
            name='temp',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
