# Generated by Django 2.0 on 2017-12-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konsola', '0003_auto_20171230_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pomiar',
            new_name='Read',
        ),
    ]
