# Generated by Django 2.0 on 2017-12-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsola', '0004_auto_20171230_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='def', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='valve',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='watering',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
